services:

  fishtts-speech-nt:
    image: fishaudio/fish-speech:v1.5.1-dev
    ports:
      - "22231:7860"
    volumes:
      - ./fish-tts:/app
    command: "python -m tools.run_webui --compile ${SPEECH_CUDA_DEVICE_ARG}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]